### ISSUE TITLE
Can you adapt this one? (even less VRAM)

### ISSUE THREAD

**Issue by ZeroCool22** [smy20011/dreambooth-docker#3]
https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth

**Comment by smy20011** [comment]
Yes, do have a plan to do that

**Comment by smy20011** [comment]
Fixed in 5ec6c56

**Comment by ZeroCool22** [comment]
> Fixed in [5ec6c56](https://github.com/smy20011/efficient-dreambooth/commit/5ec6c561bf2641a61d003007e3c22fd8bfc7845f)

Man, thank you very much, now i only need to see if i can install all the thing by myself, lol.

**PD:** Gave you an STAR to your project.
