### ISSUE TITLE
Readme example is broken with --use-auth-token

### ISSUE THREAD

**Issue by jtkelm2** [smy20011/dreambooth-docker#6]
`--use-auth-token` isn't a valid flag for `train_dreambooth.py`, and it currently breaks the example below:
![image](https://user-images.githubusercontent.com/28983469/196821724-6e6d16c0-5009-4813-8c03-d2d2f6196b02.png)

**Comment by smy20011** [comment]
Fixed [3e39510](https://github.com/smy20011/dreambooth-docker/commit/3e395107a340237c9ba546d71a668b33a67c4f67)
